name: BuyAndSell
version: ${project.version}
main: me.davidfire1332.buyandsell.BuyAndSell
api-version: 1.13
authors: [davidfire1332]
description: Enables users to buy and sell ingame items.
depend: [Vault]
commands:
  buy:
    description: Buys an item.
    usage: /<command> item amount
    permission: BuyAndSell.buyItems

  setprice:
    aliases: setprices
    description: Sets the buy and sell prices of an item.
    usage: /<command> item buyprice sellprice
    permission: BuyAndSell.setPrices

  setsellprice:
    description: Sets the sell price of an item.
    usage: /<command> item price
    permission: BuyAndSell.setPrices

  setbuyprice:
    description: Sets the buy price of an item.
    usage: /<command> item price
    permission: BuyAndSell.setPrices

  removeprice:
    aliases: removeprices
    description: Removes a price from the price list.
    usage: /<command> item
    permission: BuyAndSell.setPrices

  sell:
    description: Sells an item.
    usage: /<command> item amount
    permission: BuyAndSell.sellItems

  price:
    description: Checks the price of an item.
    usage: /<command> item
    permission: BuyAndSell.checkPrices

  pricelist:
    aliases: priceslist
    usage: /<command> page#
    permission: BuyAndSell.viewPriceList